// Create tables
CREATE TABLE todo (
  id    BIGINT generated BY DEFAULT AS IDENTITY,
  done  BOOLEAN NOT NULL,
  title CLOB,
  PRIMARY KEY (id)
);

// Insert initial data
INSERT INTO todo (title, done) VALUES ('Avoid excessive caffeine', TRUE);
INSERT INTO todo (title, done) VALUES ('Be less provocative', FALSE);
INSERT INTO todo (title, done) VALUES ('Be nice to people', FALSE);